"""utils/pdf_gen.py — ReportLab Hindi Resume Generator"""
from __future__ import annotations

import os
from pathlib import Path
from typing import List

ROOT = Path(__file__).parent.parent
FONT_PATH = ROOT / "fonts" / "NotoSansDevanagari-Regular.ttf"
RESUMES_DIR = ROOT / "data" / "resumes"

# Brand colors
ORANGE  = (0.976, 0.451, 0.086)   # #F97316
DARK_BG = (0.051, 0.051, 0.051)   # #0D0D0D
SURFACE = (0.102, 0.102, 0.102)   # #1A1A1A
WHITE   = (0.961, 0.961, 0.961)   # #F5F5F5
MUTED   = (0.420, 0.447, 0.502)   # #6B7280


def generate_resume_pdf(
    worker_id: str,
    name: str,
    phone: str,
    city: str,
    pin_code: str,
    skills: List[str],
    experience_years: int,
    preferred_wage_per_day: int,
) -> str:
    """
    Generate a single-page Hindi resume PDF.
    Returns path to the PDF file.
    """
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import mm
    from reportlab.pdfgen import canvas
    from reportlab.pdfbase import pdfmetrics
    from reportlab.pdfbase.ttfonts import TTFont
    from ui.strings_hi import (
        RESUME_SKILLS_LABEL, RESUME_EXP_LABEL,
        RESUME_CITY_LABEL, RESUME_WAGE_LABEL,
        RESUME_PHONE_LABEL, RESUME_HEADER_TAG,
        SKILL_LABELS_HI,
    )

    RESUMES_DIR.mkdir(parents=True, exist_ok=True)
    out_path = str(RESUMES_DIR / f"{worker_id}.pdf")

    # Register Hindi font
    hindi_font = "Helvetica"  # fallback
    if FONT_PATH.exists():
        try:
            pdfmetrics.registerFont(TTFont("NotoDevanagari", str(FONT_PATH)))
            hindi_font = "NotoDevanagari"
        except Exception:
            pass

    W, H = A4
    c = canvas.Canvas(out_path, pagesize=A4)

    # ── Background ─────────────────────────────────────────────────────────────
    c.setFillColorRGB(*DARK_BG)
    c.rect(0, 0, W, H, fill=1, stroke=0)

    # ── Header bar ─────────────────────────────────────────────────────────────
    c.setFillColorRGB(*ORANGE)
    c.rect(0, H - 80, W, 80, fill=1, stroke=0)

    # Logo text
    c.setFillColorRGB(*WHITE)
    c.setFont("Helvetica-Bold", 22)
    c.drawString(20, H - 45, "RozgarAI")

    c.setFont("Helvetica", 10)
    c.setFillColorRGB(*DARK_BG)
    c.drawString(20, H - 65, RESUME_HEADER_TAG)

    # ── Name ──────────────────────────────────────────────────────────────────
    c.setFillColorRGB(*WHITE)
    c.setFont("Helvetica-Bold", 28)
    c.drawString(20, H - 120, name)

    c.setFont("Helvetica", 13)
    c.setFillColorRGB(*MUTED)
    c.drawString(20, H - 142, phone)

    # ── Divider ───────────────────────────────────────────────────────────────
    c.setStrokeColorRGB(*ORANGE)
    c.setLineWidth(2)
    c.line(20, H - 155, W - 20, H - 155)

    # ── Skills section ─────────────────────────────────────────────────────────
    y = H - 180
    c.setFont(hindi_font, 13)
    c.setFillColorRGB(*ORANGE)
    c.drawString(20, y, RESUME_SKILLS_LABEL)

    y -= 28
    x_pill = 20
    for skill in skills:
        label = SKILL_LABELS_HI.get(skill, skill)
        pill_w = len(label) * 8 + 20
        # Pill background
        c.setFillColorRGB(0.486, 0.227, 0.039)  # #7C3A0A
        c.roundRect(x_pill, y - 4, pill_w, 22, 8, fill=1, stroke=0)
        # Pill text
        c.setFillColorRGB(*ORANGE)
        c.setFont(hindi_font, 11)
        c.drawString(x_pill + 10, y + 4, label)
        x_pill += pill_w + 10
        if x_pill > W - 80:
            x_pill = 20
            y -= 32

    # ── Info grid ─────────────────────────────────────────────────────────────
    y -= 50
    c.setStrokeColorRGB(0.176, 0.176, 0.176)
    c.setLineWidth(1)
    c.line(20, y + 10, W - 20, y + 10)

    def info_row(label_hi: str, value: str, y_pos: float) -> None:
        c.setFont(hindi_font, 11)
        c.setFillColorRGB(*MUTED)
        c.drawString(25, y_pos, label_hi)
        c.setFont("Helvetica-Bold", 13)
        c.setFillColorRGB(*WHITE)
        c.drawString(200, y_pos, value)
        c.setStrokeColorRGB(0.176, 0.176, 0.176)
        c.line(20, y_pos - 8, W - 20, y_pos - 8)

    info_row(RESUME_EXP_LABEL,  f"{experience_years} saal",       y - 10)
    info_row(RESUME_CITY_LABEL, f"{city} - {pin_code}",            y - 40)
    info_row(RESUME_WAGE_LABEL, f"Rs. {preferred_wage_per_day}/din", y - 70)
    info_row(RESUME_PHONE_LABEL, phone,                              y - 100)

    # ── Footer ─────────────────────────────────────────────────────────────────
    c.setFont("Helvetica", 9)
    c.setFillColorRGB(*MUTED)
    c.drawCentredString(W / 2, 25, "Generated by RozgarAI  •  rozgarai.in  •  Kaam Khojo. Kaam Do. Aaj.")

    c.save()
    return out_path
